language: ruby

sudo: required
cache: bundler

services:
 - mysql

dist: trusty

before_install:
  - jdk_switcher use openjdk8
  - gem update --system
  - gem update bundler
  - ./.travis-install-dependencies.sh

before_script:
  - jdk_switcher use $JDK

script: 'bundle exec rake test:spec test:remote:spec'

notifications:
  email:
    - kill-bill-commits@googlegroups.com

env:
  global:
    - DB_ADAPTER=mariadb DB_USER='root' DB_PORT=3306 JRUBY_OPTS='-J-Xmx1024m --debug -J-Djava.security.egd=file:/dev/./urandom'

matrix:
  include:
    # Users with legacy environments
    - rvm: ree-1.8.7-2011.12
    - rvm: 1.8.7
    - rvm: 1.9.3
    # KPM
    - rvm: 2.2.2
    # Kaui
    - rvm: 2.4.2
    # Kaui standalone
    - rvm: jruby-9.1.14.0
    # Plugins
    - rvm: jruby-1.7.26
      env: JDK=openjdk8
  fast_finish: true
