language: ruby

sudo: required
cache: bundler

dist: trusty

before_install:
  - sudo sysctl -w net.ipv4.tcp_fin_timeout=15
  - sudo sysctl -w net.ipv4.tcp_tw_reuse=1
  - travis_retry gem install bundler
  - travis_retry curl -LO 'https://search.maven.org/remotecontent?filepath=org/kill-bill/billing/killbill-profiles-killbill/0.18.14/killbill-profiles-killbill-0.18.14-jetty-console.war' && java -Dorg.killbill.catalog.uri=SpyCarAdvanced.xml -Djava.security.egd=file:/dev/./urandom -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -jar killbill-profiles-killbill-0.18.14-jetty-console.war --port 8080 --headless 2>&1 | egrep -v "lvl='INFO'| < | > |[ \t]*at [ \ta-zA-Z0-9\.\:\(\)]+" & sleep 100 && travis_retry curl -v -X POST -u 'admin:password' -H 'Content-Type:application/json' -H 'X-Killbill-CreatedBy:admin' -d '{"apiKey":"bob", "apiSecret":"lazar"}' "http://127.0.0.1:8080/1.0/kb/tenants?useGlobalDefault=true"

before_script:
  - jdk_switcher use $JDK

script: 'bundle exec rake test:spec test:remote:spec'

notifications:
  email:
    - kill-bill-commits@googlegroups.com

env:
  global:
    - JRUBY_OPTS='--2.0 -J-Xmx1024M'

matrix:
  include:
    - rvm: ree-1.8.7-2011.12
    - rvm: 1.8.7
    - rvm: 1.9.3
    - rvm: 2.2.0
    - rvm: 2.4.2
    - rvm: ruby-head
    - rvm: jruby-1.7.26
      env: JDK=oraclejdk8
    - rvm: jruby-1.7.26
      env: JDK=openjdk8
    - rvm: jruby-head
      env: JDK=oraclejdk8
    - rvm: jruby-head
      env: JDK=openjdk8
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
