language: ruby

sudo: required
cache: bundler

services:
 - mysql

dist: trusty

before_install:
  - jdk_switcher use openjdk8
  - ./.travis-install-dependencies.sh

before_script:
  - jdk_switcher use $JDK

script: 'bundle exec rake test:spec test:remote:spec'

notifications:
  email:
    - kill-bill-commits@googlegroups.com

env:
  global:
    - DB_ADAPTER=mariadb DB_USER='root' DB_PORT=3306 JRUBY_OPTS='-J-Xmx1024m --debug -J-Djava.security.egd=file:/dev/./urandom'

matrix:
  include:
    - rvm: ree-1.8.7-2011.12
    - rvm: 1.8.7
    - rvm: 1.9.3
    - rvm: 2.2.0
    - rvm: 2.4.2
    - rvm: ruby-head
    - rvm: jruby-1.7.26
      env: JDK=openjdk8
    - rvm: jruby-head
      env: JDK=openjdk8
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: 1.8.7
    - rvm: 1.9.3
    - rvm: 2.2.0
    - rvm: jruby-1.7.26
  fast_finish: true
